version: '3.8'

services:
#Levanta laravel
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "80:80"
    environment:
      - APP_ENV=
      - DB_CONNECTION=
      - DB_HOST=
      - DB_PORT=3306
      - DB_DATABASE=
      - DB_USERNAME=
      - DB_PASSWORD=
    depends_on:
      - db
    networks:
      - app_network