services:
  #Frontend
  frontend:
    image: node:20-alpine
    container_name: xuxemons_angular
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "4200:4200"
    command: sh -c "cd /app && npm install && npm start -- --host 0.0.0.0"  #Este comando mantiene el contenedor vivo para que podamos instalar Angular primero
    networks:
      - app-network

  # Backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: xuxemons_laravel
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8000:80"
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: xuxemons_db
      DB_USERNAME: xuxemons_user
      DB_PASSWORD: 1234
    networks:
      - app-network
    depends_on:
      - db

  #Base de datos
  db:
    image: mysql:8.0
    container_name: xuxemons_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: xuxemons_db
      MYSQL_USER: xuxemons_user
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 4321
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local